export default {
  ChartHistogram: {
    name: '柱状图',
    titleSize: '16',
    titleColor:'#000000',
    unit: '',
    // unitL: '',
    // unitR: '',
    titleWeight: 10,
    bold: true,
    slant: false,
    underline: false,
    showType: 'base',
    stepType: 'stepSize',
    stepDic: [
      {
        label:"步长",
        value:'stepSize'
      },
      {
        label:'分组',
        value:'group'
      }
    ],
    step: 2, // 直方图的步长
    segm: 5,
    showTextType: 'resident',
    tiny: false, // 是否开启简洁(极小)模式
    dataZoom: false, // 是否开启缩放模式
    theme: 'default',
    useThemeGradient: false, // 是否使用渐变
    showLegend: true,
    showTooltip: true,
    legendPos: 'bottom', // 图例位置
    isStack: false, // 堆叠
    tragetLines: [],
    useBack: false,
    cardBackColor: '#ffffff',
    cardBackImg: {
      backImg:''
    },
    useBorder: false,
    borderStyle: 'solid',
    borderWidth: '1',
    borderColor: '#ffffff',
    useBorderRadius :false,
    radiusTopLeft: 4,
    radiusTopRight: 4,
    radiusBottomLeft: 4,
    radiusBottomRight: 4,
    useShadow: false,
    shadowX: 0,
    shadowY: 0,
    shadowFuzzy: 10,
    shadowColor: '#ffffff',
  },
  ChartLine: {
    name: '折线图',
    titleWeight: 10,
    titleSize: '16',
    titleColor: '#000000',
    bold: true,
    slant: false,
    underline: false,
    unit: '',
    tiny: false, // 是否开启简洁(极小)模式
    dataZoom: false, // 是否开启缩放模式
    theme: '',
    useThemeGradient: false, //是否使用渐变
    showLegend: true, // 是否显示图例
    showTooltip: true, // 是否展示提示信息
    legendPos: 'bottom', // 图例位置
    tragetLines: [],
    useBack: false,
    cardBackColor: '#ffffff',
    cardBackImg: {
      backImg:''
    },
    useBorder: false,
    borderStyle: 'solid',
    borderWidth: '1',
    borderColor: '#ffffff',
    useBorderRadius: false,
    radiusTopLeft: 4,
    radiusTopRight: 4,
    radiusBottomLeft: 4,
    radiusBottomRight: 4,
    useShadow: false,
    shadowX: 0,
    shadowY: 0,
    shadowFuzzy: 10,
    shadowColor: '#ffffff',
  },
  ChartPie: {
    name: '饼图',
    titleWeight: 10,
    titleSize: '16',
    titleColor: '#000000',
    bold: true,
    slant: false,
    underline: false,
    inRadius: 0, // 内半径
    outRadius: 80, // 外半径
    theme: '',        
    useThemeGradient: false, // 是否使用渐变    
    showLegend: true, // 是否显示图例
    showTooltip: true, // 是否展示提示信息
    legendPos: 'bottom',
    showLabel: true, // 是否显示标签
    labelPosition: 'outside', // 标签显示方式
    useBack: false,
    cardBackColor: '#ffffff',
    cardBackImg:{
      backImg:''
    },
    useBorder: false,
    borderStyle: 'solid',
    borderWidth: '1',
    borderColor: '#ffffff',
    useBorderRadius: false,
    radiusTopLeft: 4,
    radiusTopRight: 4,
    radiusBottomLeft: 4,
    radiusBottomRight: 4,
    useShadow: false,
    shadowX: 0,
    shadowY: 0,
    shadowFuzzy: 10,
    shadowColor: '#ffffff',
  },
  DataCards: {
    componentName: '',
    titleWeight: 10,
    titleSize: '14',
    titleColor: '#6f7588',
    titleBold: false,
    titleSlant: false,
    titleUnderline: false,
    contentBold: true,
    contentSlant: false,
    contentUnderline: false,
    contentWeight: 10,
    contentSize: '28',    
    contentColor: '#363b4c',
    contentAlign: 'center',
    contentSpac: '0px',
    unitText: '',
    unitSize: '12',
    unitColor: '#6f7588',
    unitBold: false,
    unitSlant: false,
    unitUnderline: false,
    useIcon: true,
    iconPos: 'left',
    iconObj: {
      value: '',
      type: 'custom'
    },
    iconColor: '#000000',
    iconBackColor: '#ffffff',
    iconBackType: 'pureColor',
    backRadiusType: 'tech',
    backRadius: '0',
    cardAlign: 'left',
    useBack: false,
    cardBackColor: '#ffffff',
    cardBackImg: {
      backImg: ''
    },
    useBorder: false,
    borderStyle: 'solid',
    borderWidth: '1',
    borderColor: '#ffffff',
    useBorderRadius: false,
    useLockBorder: false,
    radiusTopLeft: 4,
    radiusTopRight: 4,
    radiusBottomLeft: 4,
    radiusBottomRight: 4,
    useShadow: false,
    shadowX: 0,
    shadowY: 0,
    shadowFuzzy: 10,
    shadowColor: '#ffffff',
  },
  CodeCards: {
    componentName: '',
    titleWeight: 10,
    titleSize: '18',
    titleColor: '#333333',
    bold: true,
    slant: false,
    underline: false,
    useBack: true,
    cardBackColor: '#ffffff',
    cardBackImg: {
      backImg: ''
    },
    useBorder: false,
    borderStyle: 'solid',
    borderWidth: '1',
    borderColor: '#ffffff',
    useBorderRadius: false,
    useLockBorder: false,
    radiusTopLeft: 4,
    radiusTopRight: 4,
    radiusBottomLeft: 4,
    radiusBottomRight: 4,
    useShadow: false,
    shadowX: 0,
    shadowY: 0,
    shadowFuzzy: 10,
    shadowColor: '#ffffff',
  },
  Label: {
    name: '',
    titleWeight: 10,
    titleSize: '16',
    titleColor: '#d8d8d8',
    position: 5,
    bold: true,
    slant: false,
    underline: false,
    useBack: false,
    cardBackColor: '#ffffff',
    cardBackImg: {
      backImg: ''
    },
    useBorder: false,
    borderStyle: 'solid',
    borderWidth: '1',
    borderColor: '#ffffff',
    useBorderRadius: false,
    useLockBorder: false,
    radiusTopLeft: 4,
    radiusTopRight: 4,
    radiusBottomLeft: 4,
    radiusBottomRight: 4,
    useShadow: false,
    shadowX: 0,
    shadowY: 0,
    shadowFuzzy: 10,
    shadowColor: '#ffffff',
  },
  // OA: {
  //   name: '',
  //   titleWeight: 10,
  //   titleSize: '20',
  //   titleColor: '#363B4C',
  //   bold: true,
  //   slant: false,
  //   underline: false,
  //   contentBold: true,
  //   contentSlant: false,
  //   contentUnderline: false,
  //   contentWeight: 10,
  //   contentSize: '12',    
  //   contentColor: '#333333',
  //   contentBackColor: '#F5F6F7',
  //   contentBackType: 'pureColor',
  //   useBack: false,
  //   cardBackColor: '#ffffff',
  //   cardBackImg: {
  //     backImg: ''
  //   },
  //   useBorder: false,
  //   borderStyle: 'solid',
  //   borderWidth: '1',
  //   borderColor: '#ffffff',
  //   useBorderRadius: false,
  //   useLockBorder: false,
  //   radiusTopLeft: 4,
  //   radiusTopRight: 4,
  //   radiusBottomLeft: 4,
  //   radiusBottomRight: 4,
  //   useShadow: false,
  //   shadowX: 0,
  //   shadowY: 0,
  //   shadowFuzzy: 10,
  //   shadowColor: '#ffffff',
  // },
  public: {
    name: '',
    titleWeight: 10,
    titleSize: '20',
    titleColor: '#363B4C',
    bold: true,
    slant: false,
    underline: false,
    useBack: false,
    cardBackColor: '#ffffff',
    cardBackImg: {
      backImg: ''
    },
    useBorder: false,
    borderStyle: 'solid',
    borderWidth: '1',
    borderColor: '#ffffff',
    useBorderRadius: false,
    useLockBorder: false,
    radiusTopLeft: 4,
    radiusTopRight: 4,
    radiusBottomLeft: 4,
    radiusBottomRight: 4,
    useShadow: false,
    shadowX: 0,
    shadowY: 0,
    shadowFuzzy: 10,
    shadowColor: '#ffffff',
  },
  ProcessManagement: {
    componentName: '',
    titleWeight: 10,
    titleSize: '14',
    titleColor: '#6f7588',
    titleBold: false,
    titleSlant: false,
    titleUnderline: false,
    contentBold: true,
    contentSlant: false,
    contentUnderline: false,
    contentWeight: 10,
    contentSize: '28',    
    contentColor: '#363b4c',
    contentAlign: 'center',
    contentSpac: '0px',
    useIcon: true,
    iconPos: 'left',
    iconObj: {
      value: '',
      type: 'custom'
    },
    iconColor: '#000000',
    iconBackColor: '#ffffff',
    iconBackType: 'pureColor',
    backRadiusType: 'tech',
    backRadius: '0',
    cardAlign: 'left',
    useBack: false,
    cardBackColor: '#ffffff',
    cardBackImg: {
      backImg: ''
    },
    useBorder: false,
    borderStyle: 'solid',
    borderWidth: '1',
    borderColor: '#ffffff',
    useBorderRadius: false,
    useLockBorder: false,
    radiusTopLeft: 4,
    radiusTopRight: 4,
    radiusBottomLeft: 4,
    radiusBottomRight: 4,
    useShadow: false,
    shadowX: 0,
    shadowY: 0,
    shadowFuzzy: 10,
    shadowColor: '#ffffff',
  },
  CRUD: {
    name: '',
    titleWeight: 10,
    titleSize: '20',
    titleColor: '#363B4C',
    bold: true,
    slant: false,
    underline: false,
    backRadiusType: 'tech',
    backRadius: '0',
    useBack: false,
    cardBackColor: '#ffffff',
    cardBackImg: {
      backImg: ''
    },
    useBorder: false,
    borderStyle: 'solid',
    borderWidth: '1',
    borderColor: '#ffffff',
    useBorderRadius: false,
    useLockBorder: false,
    radiusTopLeft: 4,
    radiusTopRight: 4,
    radiusBottomLeft: 4,
    radiusBottomRight: 4,
    useShadow: false,
    shadowX: 0,
    shadowY: 0,
    shadowFuzzy: 10,
    shadowColor: '#ffffff',
  }
}